### ISSUE TITLE
Live preview is not available 

### ISSUE THREAD

**Issue by xdandyx** [instant-markdown/instant-markdown-d#63]
# Problem summary

## Expected

Live preview is not available with instant-markdown-d@0.2.0.rc1 .
If I rollback to lower version ,it works very well except that no mathjax support.

## Environment Information

 * OS:Linux mint
 * Vim / Neovim version:8.0
 * Browser:Firefox

## Provide the output of test command (required)

Run `npm test&; sleep 5; npm stop` or at least equivalent of
`cd tests; cat test_math.md | instant-markdown-d --mathjax --debug` and paste the
console output here:

```sh

```

## Generate logfiles if appropriate

 1. package-lock.json / yarn.lock
 2. minimal `~/.vimrc` or `~/.config/nvim/init.vim` where variables for `vim-instant-markdown` defined
 3. `debug.html`

## Steps to reproduce the issue (required)

Start with command you used to install `instant-markdown-d`

 1.sudo npm install -g instant-markdown-d@0.2.0.rc1
 2.
 3.

**Comment by ashwinvis** [comment]
By "live preview" do you mean while 

1. editing the markdown file or
2. while simply opening the file

**Comment by xdandyx** [comment]
I mean it works out of expectation when editing the markdown file.

**The result of testing is : **

```
user@15:51:00>instant-markdown-d$ sudo cat tests/test_math.md | instant-markdown-d --mathjax --debug
instant-mardown-d version: v0.2.0-rc.1
nodejs version: v8.10.0
Run the following to manually open browser: 
    xdg-open http://localhost:8090/
Rendered html saved as debug.html
Error: Uncaught [Error: EACCES: permission denied, open 'debug.html']
    at reportException (/usr/local/lib/node_modules/instant-markdown-d/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
    at processJavaScript (/usr/local/lib/node_modules/instant-markdown-d/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:192:7)
    at HTMLScriptElementImpl._innerEval (/usr/local/lib/node_modules/instant-markdown-d/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:122:5)
    at /usr/local/lib/node_modules/instant-markdown-d/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:31:22
    at Object.check (/usr/local/lib/node_modules/instant-markdown-d/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:76:11)
    at /usr/local/lib/node_modules/instant-markdown-d/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:95:12
    at wrappedEnqueued (/usr/local/lib/node_modules/instant-markdown-d/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:253:16)
    at ReadStream.readableStream.on (/usr/local/lib/node_modules/instant-markdown-d/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:74:7)
    at emitNone (events.js:111:20)
    at ReadStream.emit (events.js:208:7) { Error: EACCES: permission denied, open 'debug.html'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.writeFileSync (fs.js:1299:33)
    at /usr/local/lib/node_modules/instant-markdown-d/instant-markdown-d:103:16
    at typeset (/usr/local/lib/node_modules/instant-markdown-d/node_modules/mathjax-node-page/lib/main.js:380:17)
    at ReturnResult (/usr/local/lib/node_modules/instant-markdown-d/node_modules/mathjax-node/lib/main.js:874:3)
    at Function.execute (file:///usr/local/lib/node_modules/instant-markdown-d/node_modules/mathjax/unpacked/MathJax.js:243:26)
    at cb (file:///usr/local/lib/node_modules/instant-markdown-d/node_modules/mathjax/unpacked/MathJax.js:225:59)
    at Object.Process (file:///usr/local/lib/node_modules/instant-markdown-d/node_modules/mathjax/unpacked/MathJax.js:495:38)
    at Object.call (file:///usr/local/lib/node_modules/instant-markdown-d/node_modules/mathjax/unpacked/MathJax.js:508:37)
    at Function.WAITEXECUTE (file:///usr/local/lib/node_modules/instant-markdown-d/node_modules/mathjax/unpacked/MathJax.js:348:50)
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: 'debug.html' }
connection established!Formula \Sigma_{i=0}^\infty \frac{1}{n} = 2 contains the following errors:
 [ 'Error: Error: EACCES: permission denied, open \'debug.html\'\n    at Object.fs.openSync (fs.js:646:18)\n    at Object.fs.writeFileSync (fs.js:1299:33)\n    at /usr/local/lib/node_modules/instant-markdown-d/instant-markdown-d:103:16\n    at typeset (/usr/local/lib/node_modules/instant-markdown-d/node_modules/mathjax-node-page/lib/main.js:380:17)\n    at ReturnResult (/usr/local/lib/node_modules/instant-markdown-d/node_modules/mathjax-node/lib/main.js:874:3)\n    at Function.execute (file:///usr/local/lib/node_modules/instant-markdown-d/node_modules/mathjax/unpacked/MathJax.js:243:26)\n    at cb (file:///usr/local/lib/node_modules/instant-markdown-d/node_modules/mathjax/unpacked/MathJax.js:225:59)\n    at Object.Process (file:///usr/local/lib/node_modules/instant-markdown-d/node_modules/mathjax/unpacked/MathJax.js:495:38)\n    at Object.call (file:///usr/local/lib/node_modules/instant-markdown-d/node_modules/mathjax/unpacked/MathJax.js:508:37)\n    at Function.WAITEXECUTE (file:///usr/local/lib/node_modules/instant-markdown-d/node_modules/mathjax/unpacked/MathJax.js:348:50)' ]
Rendered html saved as debug.html
Error: Uncaught [Error: EACCES: permission denied, open 'debug.html']
    at reportException (/usr/local/lib/node_modules/instant-markdown-d/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
    at processJavaScript (/usr/local/lib/node_modules/instant-markdown-d/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:192:7)
    at HTMLScriptElementImpl._innerEval (/usr/local/lib/node_modules/instant-markdown-d/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:122:5)
    at /usr/local/lib/node_modules/instant-markdown-d/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:31:22
    at Object.check (/usr/local/lib/node_modules/instant-markdown-d/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:76:11)
    at /usr/local/lib/node_modules/instant-markdown-d/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:95:12
    at wrappedEnqueued (/usr/local/lib/node_modules/instant-markdown-d/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:253:16)
    at ReadStream.readableStream.on (/usr/local/lib/node_modules/instant-markdown-d/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:74:7)
    at emitNone (events.js:111:20)
    at ReadStream.emit (events.js:208:7) { Error: EACCES: permission denied, open 'debug.html'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.writeFileSync (fs.js:1299:33)
    at /usr/local/lib/node_modules/instant-markdown-d/instant-markdown-d:103:16
    at typeset (/usr/local/lib/node_modules/instant-markdown-d/node_modules/mathjax-node-page/lib/main.js:380:17)
    at ReturnResult (/usr/local/lib/node_modules/instant-markdown-d/node_modules/mathjax-node/lib/main.js:874:3)
    at Function.execute (file:///usr/local/lib/node_modules/instant-markdown-d/node_modules/mathjax/unpacked/MathJax.js:243:26)
    at cb (file:///usr/local/lib/node_modules/instant-markdown-d/node_modules/mathjax/unpacked/MathJax.js:225:59)
    at Object.Process (file:///usr/local/lib/node_modules/instant-markdown-d/node_modules/mathjax/unpacked/MathJax.js:495:38)
    at Object.call (file:///usr/local/lib/node_modules/instant-markdown-d/node_modules/mathjax/unpacked/MathJax.js:508:37)
    at Function.WAITEXECUTE (file:///usr/local/lib/node_modules/instant-markdown-d/node_modules/mathjax/unpacked/MathJax.js:348:50)
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: 'debug.html' }

```

**Comment by ashwinvis** [comment]
Don't use sudo to run the test. Also, copy the test file and run it in your home directory and then run the test so you have permissions. Then attach the debug.html that you get.

**Comment by xdandyx** [comment]
` { Error: EACCES: permission denied, open 'debug.html'}`
This problem is solved by run `sudo chmod 777 -R ./*`

Then,I rerun ` sudo cat tests/test_math.md | instant-markdown-d --mathjax --debug`,`debug.html` is generated normally.However,it seems normal.

The `debug.html` is not supported file type ,so,I rename it to `debug.txt` .

And,I attached a `.png` file which is grasp from Firefox.
[debug.txt](https://github.com/suan/instant-markdown-d/files/3420919/debug.txt)
![2019-07-23 16-09-36屏幕截图](https://user-images.githubusercontent.com/20438962/61694749-b5cda980-ad64-11e9-8e70-e0320e5334fe.png)

**Comment by ashwinvis** [comment]
So it works. The message "Live preview is unavailable" will happen when the `instant-markdown-d` server is stopped.

**Comment by xdandyx** [comment]
So did who stop the `instant-markdown-d` server?

I always edit a `.md` file with `vim xx.md`,then  firefox is opened . If I keep editing the file ,the new content will not appear .This step can't be shown by running `cat xx.md | instant-markdown-d --debug`.

 The formulas are always rendered correctly .

**Comment by ashwinvis** [comment]
Then it is an issue with how instant-markdown-d is started by Vim. We need a way to debug this in Vim... I will see if it is possible. Thanks for the issue report!

**Comment by xdandyx** [comment]
Ok, thank u!

**Comment by ashwinvis** [comment]
Okay that is weird. I thought the node server died while open vim. But now you say it still persists...

Anyways it is a beta release. So keep using the stable one for now. :)

**Comment by xdandyx** [comment]
OK.

**Comment by ashwinvis** [comment]
With suan/vim-instant-markdown#161 you should be able to debug this from vim. Do try it.

**Comment by xdandyx** [comment]
Could you tell me how to do it ?

Do you mean : 
1. git clone `vim-instant-markdown` from master into `.vim/bundle/` 
2. then `vim xx.md`
3. check the log

**Comment by ashwinvis** [comment]
It is mentioned in the readme

> If you do not use a plugin manager, copy the after/ftplugin/markdown/instant-markdown.vim file into ~/.vim/after/ftplugin/markdown/ (creating directories as necessary),

And then 

> For troubleshooting, server startup and curl communication from Vim to the server can be logged into a file.

> let g:instant_markdown_logfile = '/tmp/instant_markdown.log'

Then do steps 2 and 3

**Comment by xdandyx** [comment]
Okay, I will try it.

**Comment by ashwinvis** [comment]
Thanks for that. I will fix the port option right away.

**Comment by xdandyx** [comment]
Okay.

**Comment by ashwinvis** [comment]
A lot has changed now and a new version is out, so I hope this is no longer an issue. I would close this issue now.
